# Generated by Django 5.2.7 on 2025-10-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_category_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='hierarchy',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
