# Generated by Django 5.2.7 on 2025-11-03 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_lesson_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['-updated_at']},
        ),
    ]
