# Generated by Django 5.2.7 on 2025-11-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_lesson_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='lessons',
            field=models.ManyToManyField(to='main_app.lesson'),
        ),
    ]
