# Generated by Django 5.2.7 on 2025-11-03 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_category_lessons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='lessons',
        ),
        migrations.AddField(
            model_name='lesson',
            name='category',
            field=models.ForeignKey(default=57, on_delete=django.db.models.deletion.CASCADE, to='main_app.category'),
            preserve_default=False,
        ),
    ]
