# Generated by Django 5.2.7 on 2025-11-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_category_lessons_lesson_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
