# Generated by Django 5.2.7 on 2025-11-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_usercategoryscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
