# Generated by Django 5.2.7 on 2026-04-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_category_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
