# Generated by Django 5.2.7 on 2026-05-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='max_reached_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
