# Generated by Django 5.2.7 on 2026-05-22 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_userprofile_max_reached_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='max_reached_date',
            new_name='last_call_date',
        ),
    ]
